[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend/auth_api && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/auth/health/"
restartPolicyType = "on_failure"
