[build]
builder = "nixpacks"

[env]
CORS_ALLOWED_ORIGINS = "https://auth-demo-bay.vercel.app"

[deploy]
startCommand = "gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/auth/health/"
restartPolicyType = "on_failure"

[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend/auth_api && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/auth/health/"
restartPolicyType = "on_failure"
